#ifndef	HWM_MINIVSTEFFECT_MINIVSTEFFECT_VSTHEADERINCLUDE_HPP
#define	HWM_MINIVSTEFFECT_MINIVSTEFFECT_VSTHEADERINCLUDE_HPP

#include "./public.sdk/source/vst2.x/audioeffectx.h"

#endif	//HWM_MINIVSTEFFECT_MINIVSTEFFECT_VSTHEADERINCLUDE_HPP
